import { Team, StationTask, MysteryClue, GameState, ActivityLogItem } from './types';

export const initialTeams: Team[] = [
  {
    id: 'team-cyan-01',
    name: 'Byte Impostors',
    leaderName: 'Aarav Sharma',
    email: 'aarav@nexus.org',
    phone: '+91 98111 22334',
    members: ['Aarav Sharma', 'Rohan Mehta', 'Sneha Kapoor', 'Divya Patel'],
    color: '#00F0FF',
    score: 850,
    tasksCompleted: 6,
    cluesSolved: 2,
    status: 'active',
    registeredEvents: ['Coded Chaos', 'Tech Mystery'],
    badgeCode: 'NEXUS-BC-901',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'team-red-02',
    name: 'Sus Overclockers',
    leaderName: 'Zoya Khan',
    email: 'zoya@nexus.org',
    phone: '+91 98222 33445',
    members: ['Zoya Khan', 'Kabir Verma', 'Ananya Singh', 'Farhan Akhtar'],
    color: '#FF0055',
    score: 720,
    tasksCompleted: 5,
    cluesSolved: 1,
    status: 'active',
    registeredEvents: ['Coded Chaos', 'Tech Mystery'],
    badgeCode: 'NEXUS-SO-412',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'team-green-03',
    name: 'Skeld Infiltrators',
    leaderName: 'Devansh Joshi',
    email: 'devansh@nexus.org',
    phone: '+91 98333 44556',
    members: ['Devansh Joshi', 'Pooja Iyer', 'Aditya Nair', 'Tanya Roy'],
    color: '#10B981',
    score: 980,
    tasksCompleted: 8,
    cluesSolved: 2,
    status: 'active',
    registeredEvents: ['Coded Chaos', 'Tech Mystery'],
    badgeCode: 'NEXUS-SI-118',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'team-yellow-04',
    name: 'Cipher Saboteurs',
    leaderName: 'Meera Deshmukh',
    email: 'meera@nexus.org',
    phone: '+91 98444 55667',
    members: ['Meera Deshmukh', 'Karan Malhotra', 'Gauri Sen', 'Vikram Batra'],
    color: '#FBBF24',
    score: 640,
    tasksCompleted: 4,
    cluesSolved: 1,
    status: 'active',
    registeredEvents: ['Coded Chaos', 'Tech Mystery'],
    badgeCode: 'NEXUS-CS-783',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'team-purple-05',
    name: 'Quantum Detectives',
    leaderName: 'Arjun Das',
    email: 'arjun@nexus.org',
    phone: '+91 98555 66778',
    members: ['Arjun Das', 'Simran Kaur', 'Nikhil Rao', 'Priya Bhatia'],
    color: '#A855F7',
    score: 1120,
    tasksCompleted: 9,
    cluesSolved: 3,
    status: 'active',
    registeredEvents: ['Coded Chaos', 'Tech Mystery'],
    badgeCode: 'NEXUS-QD-305',
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  }
];

export const initialTasks: StationTask[] = [
  {
    id: 'task-elec-01',
    title: 'Fix Logic Gates & Indentation Fault',
    room: 'Electrical',
    description: 'Fix the asynchronous race condition in the circuit breaker control script.',
    snippet: `async function powerGrid() {\n  const lights = await switchOn();\n  // BUG: Unhandled promise rejection\n}`,
    points: 100,
    status: 'completed',
    completedByTeamId: 'team-purple-05',
    completedAt: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 'task-react-02',
    title: 'Quantum Core Synchronization',
    room: 'Reactor',
    description: 'Align the resonance frequencies between Primary and Secondary coolant manifolds.',
    points: 150,
    status: 'in_progress',
  },
  {
    id: 'task-med-03',
    title: 'DNA Sample Scan & Cipher Match',
    room: 'MedBay',
    description: 'Deconvolve the synthetic nucleotide sequence left on the autopsy scanner.',
    points: 120,
    status: 'completed',
    completedByTeamId: 'team-green-03',
    completedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'task-nav-04',
    title: 'Chart Sublight Trajectory Coordinates',
    room: 'Navigation',
    description: 'Solve the Dijkstra shortest path through asteroid sector 7G.',
    points: 110,
    status: 'pending',
  },
  {
    id: 'task-admin-05',
    title: 'Swipe Holographic ID Card',
    room: 'Admin',
    description: 'Calibrate card swipe duration between 0.8s and 1.2s without jitter.',
    points: 80,
    status: 'completed',
    completedByTeamId: 'team-cyan-01',
    completedAt: new Date(Date.now() - 450000).toISOString(),
  },
  {
    id: 'task-o2-06',
    title: 'Clean Atmospheric Filter Canister',
    room: 'O2',
    description: 'Clear the particulate obstruction in oxygen filtration manifold B.',
    points: 90,
    status: 'pending',
  },
  {
    id: 'task-weap-07',
    title: 'Target Calibration & Meteor Deflection',
    room: 'Weapons',
    description: 'Calculate lead firing angle for approaching debris traveling at 0.15c.',
    points: 130,
    status: 'pending',
  },
  {
    id: 'task-comms-08',
    title: 'Descramble Transmission Beacon',
    room: 'Communications',
    description: 'Tune bandpass filter to 1420.405 MHz to eliminate foreign carrier hum.',
    points: 100,
    status: 'pending',
  }
];

export const initialMysteryClues: MysteryClue[] = [
  {
    id: 'clue-01',
    caseFile: 'DOSSIER #01: THE GHOST IN ELECTRICAL',
    title: 'The Inverted Binary Log',
    difficulty: 'Novice',
    location: 'Electrical Main Panel',
    description: 'A shredded flash drive recovered near the junction box has a corrupted raw bitstream. What secret passphrase was encoded in the binary inversion?',
    puzzleContent: '01001110 01000101 01011000 01010101 01010011 01011111 01000011 01001000 01000001 01001111 01010011',
    hint: 'Convert binary bytes to ASCII characters. Check for NEXUS prefix.',
    flagHash: 'NEXUS_CHAOS',
    points: 250,
    solvedByTeamIds: ['team-purple-05', 'team-green-03', 'team-cyan-01'],
  },
  {
    id: 'clue-02',
    caseFile: 'DOSSIER #02: MEDBAY METADATA',
    title: 'The Caesar Shift of Patient Zero',
    difficulty: 'Investigator',
    location: 'MedBay Quarantine Bio-Terminal',
    description: 'The autopsy report timestamp was encrypted with a classic cryptographic rotation (ROT-13). Decipher the infected compartment name.',
    puzzleContent: 'GUR_VZCBFGBE_VF_VAFVQR_GRPABYBTl',
    hint: 'Rotate every Latin letter forward/backward by 13 positions.',
    flagHash: 'THE_IMPOSTOR_IS_INSIDE_TECHNOLOGY',
    points: 350,
    solvedByTeamIds: ['team-purple-05', 'team-cyan-01'],
  },
  {
    id: 'clue-03',
    caseFile: 'DOSSIER #03: NAVIGATION HEX TRAIL',
    title: 'The Quantum Coordinates Hex Dump',
    difficulty: 'Cyber Detective',
    location: 'Navigation Sub-console',
    description: 'Steering telemetry was overridden. The intruder left a hexadecimal signature pointing to their secret communication channel.',
    puzzleContent: '4e 45 58 55 53 5f 52 45 44 5f 53 55 53',
    hint: 'Hexadecimal to ASCII decoder. Look for color markers.',
    flagHash: 'NEXUS_RED_SUS',
    points: 500,
    solvedByTeamIds: ['team-purple-05'],
  },
  {
    id: 'clue-04',
    caseFile: 'DOSSIER #04: THE REACTOR KEYCARD',
    title: 'Base64 Memory Leak',
    difficulty: 'Investigator',
    location: 'Lower Reactor Access Shaft',
    description: 'An intercepted packet during reactor stabilization contained an obfuscated payload string.',
    puzzleContent: 'Q09ERURfQ0hBT1NfV0lOTkVS',
    hint: 'RFC 4648 Base64 decoding reveals the victory token.',
    flagHash: 'CODED_CHAOS_WINNER',
    points: 300,
    solvedByTeamIds: [],
  }
];

export const initialGameState: GameState = {
  matchId: 'NEXUS-MATCH-2026-ALPHA',
  matchName: 'Championship Round: Chaos in Orbit',
  status: 'in_progress',
  crewmatesAlive: 8,
  impostorsCount: 2,
  totalTasks: initialTasks.length,
  completedTasksCount: initialTasks.filter(t => t.status === 'completed').length,
  sabotage: {
    active: false,
    type: null,
    title: 'Systems Nominal',
    description: 'All ship subsystems operating within normal parameters.',
    durationSeconds: 60,
    timeRemaining: 0,
    triggeredAt: null,
  },
  emergency: {
    active: false,
    caller: null,
    reason: null,
    timeRemaining: 0,
    votes: {},
  },
  startedAt: new Date(Date.now() - 1800000).toISOString(),
};

export const initialActivityLogs: ActivityLogItem[] = [
  {
    id: 'act-1',
    timestamp: new Date(Date.now() - 1700000).toISOString(),
    type: 'system',
    message: 'NEXUS: Coded Chaos match initialized in The Skeld Station.',
    severity: 'info',
  },
  {
    id: 'act-2',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    type: 'task',
    message: 'Team Quantum Detectives completed [Fix Logic Gates] in Electrical (+100 pts)',
    teamName: 'Quantum Detectives',
    severity: 'success',
  },
  {
    id: 'act-3',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    type: 'task',
    message: 'Team Skeld Infiltrators completed [DNA Sample Scan] in MedBay (+120 pts)',
    teamName: 'Skeld Infiltrators',
    severity: 'success',
  },
  {
    id: 'act-4',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    type: 'clue',
    message: 'Team Byte Impostors cracked Dossier #01: The Inverted Binary Log (+250 pts)',
    teamName: 'Byte Impostors',
    severity: 'success',
  },
  {
    id: 'act-5',
    timestamp: new Date(Date.now() - 450000).toISOString(),
    type: 'task',
    message: 'Team Byte Impostors swiped Admin ID Card in Admin (+80 pts)',
    teamName: 'Byte Impostors',
    severity: 'success',
  }
];
